// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {analysis} from '../models';
import {main} from '../models';

export function Analyze(arg1:string):Promise<analysis.SongAnalysis>;

export function AnalyzerPreparing():Promise<boolean>;

export function AudioDuration(arg1:string):Promise<number>;

export function ChooseAudioFile():Promise<string>;

export function ChooseTimelineSavePath(arg1:string):Promise<string>;

export function DiscoverDevices():Promise<Array<main.EditorDevice>>;

export function Generate(arg1:string,arg2:string,arg3:string,arg4:Array<main.EditorDevice>):Promise<main.EditorSession>;

export function GenerateFromAnalysis(arg1:string,arg2:analysis.SongAnalysis,arg3:string,arg4:string,arg5:Array<main.EditorDevice>):Promise<main.EditorSession>;

export function MasterBrightness():Promise<number>;

export function PausePreview():Promise<void>;

export function ResumePreview():Promise<void>;

export function SaveTimeline(arg1:main.SaveTimelineRequest):Promise<void>;

export function SetMasterBrightness(arg1:number):Promise<void>;

export function StartAudioPreview(arg1:string):Promise<void>;

export function StartPreview(arg1:main.PreviewRequest):Promise<void>;

export function StopPreview():Promise<void>;

export function Styles():Promise<Array<string>>;
