// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AudioDuration(arg1) {
  return window['go']['main']['App']['AudioDuration'](arg1);
}

export function ChooseAudioFile() {
  return window['go']['main']['App']['ChooseAudioFile']();
}

export function ChooseTimelineSavePath(arg1) {
  return window['go']['main']['App']['ChooseTimelineSavePath'](arg1);
}

export function DiscoverDevices() {
  return window['go']['main']['App']['DiscoverDevices']();
}

export function Generate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Generate'](arg1, arg2, arg3, arg4);
}

export function PausePreview() {
  return window['go']['main']['App']['PausePreview']();
}

export function ResumePreview() {
  return window['go']['main']['App']['ResumePreview']();
}

export function SaveTimeline(arg1) {
  return window['go']['main']['App']['SaveTimeline'](arg1);
}

export function StartAudioPreview(arg1) {
  return window['go']['main']['App']['StartAudioPreview'](arg1);
}

export function StartPreview(arg1) {
  return window['go']['main']['App']['StartPreview'](arg1);
}

export function StopPreview() {
  return window['go']['main']['App']['StopPreview']();
}

export function Styles() {
  return window['go']['main']['App']['Styles']();
}
